# 112-1 ML_HW2_Group homework
* Group: 3
* Member: 邱寶樟(26)、侯亮羽(14)、李奕呈(18)

    We will use 5 categorical features and 11 numerical features to predict y. 
    You need to follow most of the questions as in the individual homework, but emphasize the following specific questions.

## (a)
* Please use the function get_dummies() to transform the categorical features into 0 and 1 numbers.<br> 
* Inside the get_dummies() function, you could provide all of the features which is easier than the approach in the lecture note. That is, the numerical features.

In [1]:
import pandas as pd 
df = pd.read_csv("throughput.csv")
df.head()

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16
0,1546.836248,X1-1,X2-1,X3-1,X4-1,X5-1,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,0.8
1,1261.722593,X1-1,X2-1,X3-1,X4-1,X5-1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,0.8
2,860.853275,X1-1,X2-1,X3-1,X4-1,X5-1,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,0.8
3,887.356349,X1-1,X2-1,X3-1,X4-1,X5-1,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,0.8
4,895.059756,X1-1,X2-1,X3-1,X4-1,X5-1,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,0.8

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13186 entries, 0 to 13185
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Y       13186 non-null  float64
 1   X1      13186 non-null  object
 2   X2      13186 non-null  object
 3   X3      13186 non-null  object
 4   X4      13185 non-null  object
 5   X5      13186 non-null  object
 6   X6      13186 non-null  float64
 7   X7      13186 non-null  int64
 8   X8      13186 non-null  int64
 9   X9      13186 non-null  int64
 10  X10     13186 non-null  float64
 11  X11     13186 non-null  float64
 12  X12     13186 non-null  float64
 13  X13     13186 non-null  int64
 14  X14     13186 non-null  int64
 15  X15     13186 non-null  int64
 16  X16     13186 non-null  float64
dtypes: float64(6), int64(6), object(5)
memory usage: 1.7+ MB

In [3]:
throughput = df.dropna()
throughput.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13185 entries, 0 to 13185
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Y       13185 non-null  float64
 1   X1      13185 non-null  object
 2   X2      13185 non-null  object
 3   X3      13185 non-null  object
 4   X4      13185 non-null  object
 5   X5      13185 non-null  object
 6   X6      13185 non-null  float64
 7   X7      13185 non-null  int64
 8   X8      13185 non-null  int64
 9   X9      13185 non-null  int64
 10  X10     13185 non-null  float64
 11  X11     13185 non-null  float64
 12  X12     13185 non-null  float64
 13  X13     13185 non-null  int64
 14  X14     13185 non-null  int64
 15  X15     13185 non-null  int64
 16  X16     13185 non-null  float64
dtypes: float64(6), int64(6), object(5)
memory usage: 1.8+ MB

In [4]:
throughput.iloc[:, 1:6]

         X1    X2    X3    X4     X5
0      X1-1  X2-1  X3-1  X4-1   X5-1
1      X1-1  X2-1  X3-1  X4-1   X5-1
2      X1-1  X2-1  X3-1  X4-1   X5-1
3      X1-1  X2-1  X3-1  X4-1   X5-1
4      X1-1  X2-1  X3-1  X4-1   X5-1
...     ...   ...   ...   ...    ...
13181  X1-2  X2-2  X3-2  X4-7  X5-17
13182  X1-2  X2-2  X3-2  X4-7  X5-17
13183  X1-2  X2-2  X3-2  X4-7  X5-17
13184  X1-2  X2-2  X3-1  X4-7  X5-21
13185  X1-2  X2-2  X3-1  X4-7  X5-21

[13185 rows x 5 columns]

In [5]:
pd.get_dummies(throughput.iloc[:, 1:6]).head()

,X1_X1-1,X1_X1-2,X2_X2-1,X2_X2-2,X2_X2-3,X3_X3-1,X3_X3-2,X3_X3-3,X3_X3-4,X4_X4-1,...,X5_X5-20,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9
0,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [6]:
pd.get_dummies(throughput.iloc[:, 1:6]).astype(int).head()

,X1_X1-1,X1_X1-2,X2_X2-1,X2_X2-2,X2_X2-3,X3_X3-1,X3_X3-2,X3_X3-3,X3_X3-4,X4_X4-1,...,X5_X5-20,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9
0,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## (b)
* What are the most important correlation coefficients in terms of absolute magnitude with respect to the column Y? 
* Does it make a difference as compared with the numerical features only?

In [7]:
categorical = pd.get_dummies(throughput.iloc[:, 1:])
categorical

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X5_X5-20,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9
0,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,...,0,0,0,0,0,0,0,0,0,0
1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,...,0,0,0,0,0,0,0,0,0,0
2,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,...,0,0,0,0,0,0,0,0,0,0
3,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,...,0,0,0,0,0,0,0,0,0,0
4,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13181,0.149699,479,247,60,12.0,18.0,1.20,132,60,88,...,0,0,0,0,0,0,0,0,0,0
13182,0.300309,217,216,80,8.0,10.5,1.00,162,168,126,...,0,0,0,0,0,0,0,0,0,0
13183,0.300309,217,216,80,8.0,10.5,1.00,162,168,26,...,0,0,0,0,0,0,0,0,0,0
13184,0.154297,370,327,150,10.0,14.5,0.80,200,70,182,...,0,1,0,0,0,0,0,0,0,0
13185,0.163640,370,327,150,10.0,14.5,0.80,200,70,182,...,0,1,0,0,0,0,0,0,0,0

In [8]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
X_scaled = ss.fit_transform(categorical)
X_scaled.shape

(13185, 49)

In [9]:
pd.DataFrame(X_scaled, columns = categorical.columns[0:])

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X5_X5-20,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9
0,0.001773,0.057196,0.055133,0.078571,0.026316,0.000000,0.030864,0.000000,0.666110,0.010526,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.002447,0.088561,0.028517,0.078571,0.026316,0.000000,0.030864,0.000000,0.666110,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.005567,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.000000,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.007962,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.000000,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.007997,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.000000,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13180,0.010523,0.848708,0.433460,0.014286,0.263158,0.421053,0.493827,0.323760,0.023372,0.221053,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13181,0.021117,0.365314,0.374525,0.042857,0.157895,0.223684,0.370370,0.402089,0.068447,0.321053,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13182,0.021117,0.365314,0.374525,0.042857,0.157895,0.223684,0.370370,0.402089,0.068447,0.057895,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13183,0.010847,0.647601,0.585551,0.142857,0.210526,0.328947,0.246914,0.501305,0.027546,0.468421,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13184,0.011504,0.647601,0.585551,0.142857,0.210526,0.328947,0.246914,0.501305,0.027546,0.468421,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
pd.DataFrame(throughput['Y'], columns = [throughput.columns[0]])

                 Y
0      1546.836248
1      1261.722593
2       860.853275
3       887.356349
4       895.059756
...            ...
13181   129.837472
13182     7.835104
13183     7.835104
13184   128.375469
13185    74.586662

[13185 rows x 1 columns]

In [11]:
throughput['Y'].shape, X_scaled.shape

((13185,), (13185, 49))

In [12]:
data = pd.concat([pd.DataFrame(X_scaled, columns = categorical.columns[ 0:]), 
                  pd.DataFrame(throughput['Y'].values, columns = [throughput.columns[0]])], axis = 1) 
data.head() # See the result and make sure that the above command works!

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9,Y
0,0.001773,0.057196,0.055133,0.078571,0.026316,0.000000,0.030864,0.0,0.666110,0.010526,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1546.836248
1,0.002447,0.088561,0.028517,0.078571,0.026316,0.000000,0.030864,0.0,0.666110,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1261.722593
2,0.005567,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.0,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.853275
3,0.007962,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.0,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,887.356349
4,0.007997,0.289668,0.319392,0.214286,0.157895,0.105263,0.216049,0.0,0.088481,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,895.059756

In [13]:
import numpy as np
def split_train_test(data, train_ratio, random_seed):
    # to make this notebook's output identical at every run
    np.random.seed(random_seed)
    shuffled_indices = np.random.permutation(len(data))
    train_set_size = int(len(data) * train_ratio)
    # partition
    train_indices = shuffled_indices[:train_set_size]
    test_indices = shuffled_indices[train_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

train_data, test_data = split_train_test(data, 0.75 , 128 )

train_data.head(2)

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X5_X5-21,X5_X5-22,X5_X5-3,X5_X5-4,X5_X5-5,X5_X5-6,X5_X5-7,X5_X5-8,X5_X5-9,Y
1232,0.002395,0.073801,0.072243,0.091429,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1307.817487
2271,0.016920,0.164207,0.174905,0.291429,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,398.908415

In [14]:
corr_matrix = train_data.corr()
print(corr_matrix)

                X6        X7        X8        X9       X10       X11  \
X6        1.000000  0.018762 -0.134181 -0.042729  0.357182  0.166759
X7        0.018762  1.000000  0.590991 -0.036867  0.518666  0.722287
X8       -0.134181  0.590991  1.000000  0.248652  0.235019  0.585305
X9       -0.042729 -0.036867  0.248652  1.000000  0.057629  0.199473
X10       0.357182  0.518666  0.235019  0.057629  1.000000  0.769093
X11       0.166759  0.722287  0.585305  0.199473  0.769093  1.000000
X12       0.164090  0.528802  0.543090  0.351492  0.549801  0.765718
X13       0.297680  0.563607  0.476013  0.030527  0.380147  0.672183
X14      -0.234916 -0.537753 -0.515278 -0.174384 -0.686586 -0.768959
X15       0.330360  0.491966  0.362986  0.058932  0.637129  0.694751
X16       0.064682 -0.270442 -0.328241 -0.070832  0.071704 -0.122963
X1_X1-1   0.000948 -0.514958 -0.622487 -0.169023 -0.256702 -0.674788
X1_X1-2  -0.000948  0.514958  0.622487  0.169023  0.256702  0.674788
X2_X2-1   0.027401 -0.098912 -0.026453  0.003716 -0.048496  0.042346
X2_X2-2  -0.222869  0.110054  0.105140  0.087133  0.012656 -0.017861
X2_X2-3   0.400208 -0.042886 -0.164287 -0.182615  0.062345 -0.040692
X3_X3-1  -0.409764 -0.083494  0.090673  0.260238 -0.112393 -0.028434
X3_X3-2  -0.048432  0.175598  0.041625 -0.186181  0.100216  0.086769
X3_X3-3   0.578331 -0.042827 -0.157157 -0.176760  0.059916 -0.038718
X3_X3-4   0.009959  0.002055  0.020052 -0.030375  0.006335  0.007827
X4_X4-1   0.238682 -0.047119 -0.139945 -0.164494  0.023694 -0.081288
X4_X4-2   0.080051 -0.329533 -0.309430 -0.062028 -0.326995 -0.357099
X4_X4-3   0.010412  0.052155  0.021863  0.049149  0.003588  0.071500
X4_X4-4   0.109540 -0.092836 -0.125604  0.016325  0.040701 -0.044384
X4_X4-5  -0.209865  0.047219  0.292111  0.154753  0.038540  0.146911
X4_X4-6  -0.090677  0.328989  0.180049 -0.074959  0.275415  0.282389
X4_X4-7  -0.066261  0.344882  0.182133  0.045116  0.115661  0.194167
X5_X5-1  -0.237575 -0.465119 -0.459865 -0.396463 -0.600236 -0.722855
X5_X5-10 -0.020863 -0.024037 -0.025803  0.123094 -0.013361 -0.037230
X5_X5-11 -0.065755 -0.051899 -0.032302  0.031594  0.030800 -0.002327
X5_X5-12 -0.091988 -0.051197  0.027559  0.069413 -0.040304 -0.040114
X5_X5-13  0.170153 -0.188619 -0.191270  0.237652 -0.136280 -0.244493
X5_X5-14 -0.011927 -0.004163  0.003964 -0.010253  0.034206  0.011958
X5_X5-15 -0.014592  0.182183  0.062857  0.102070  0.123289  0.174486
X5_X5-16  0.263354 -0.069534 -0.273058 -0.095165  0.656762  0.206990
X5_X5-17  0.315467  0.407971 -0.009987 -0.439398  0.216344  0.206806
X5_X5-18 -0.042383  0.021164 -0.000846 -0.108568 -0.002698 -0.103076
X5_X5-19       NaN       NaN       NaN       NaN       NaN       NaN
X5_X5-2  -0.103286  0.208358  0.554086  0.475370  0.058864  0.481647
X5_X5-20       NaN       NaN       NaN       NaN       NaN       NaN
X5_X5-21 -0.047513  0.036214  0.028817 -0.144636  0.030280  0.008229
X5_X5-22 -0.026995  0.010280  0.008427  0.064785  0.000029 -0.044817
X5_X5-3  -0.037248  0.046204  0.113389 -0.047977  0.070050  0.077139
X5_X5-4   0.001207 -0.003642 -0.006012  0.003964  0.000568  0.005673
X5_X5-5  -0.031645  0.082135  0.003597  0.171631  0.053115 -0.024441
X5_X5-6  -0.009187 -0.041910 -0.022867 -0.071153  0.060109  0.007098
X5_X5-7  -0.002437  0.012291  0.011056 -0.004200  0.003348  0.004057
X5_X5-8  -0.008074 -0.007717 -0.026668 -0.085936  0.046511  0.008847
X5_X5-9  -0.031391 -0.078621 -0.082401  0.385619 -0.101415 -0.110711
Y        -0.376066 -0.520050 -0.448213 -0.179513 -0.667452 -0.747957

               X12       X13       X14       X15  ...  X5_X5-21  X5_X5-22  \
X6        0.164090  0.297680 -0.234916  0.330360  ... -0.047513 -0.026995
X7        0.528802  0.563607 -0.537753  0.491966  ...  0.036214  0.010280
X8        0.543090  0.476013 -0.515278  0.362986  ...  0.028817  0.008427
X9        0.351492  0.030527 -0.174384  0.058932  ... -0.144636  0.064785
X10       0.549801  0.380147 -0.686586  0.637129  ...  0.030280  0.000029
X11       0.765718  0.672183 -0.768959  0.694751  ...  0.008229 -0.044817
X12       1.000000  0.681071 -0.706749  0.536497  ...  0.017542 -0.040036
X13       0.681071  1.000000 -0.547023  0.627591  ... -0.001273 -0.060995
X14      -0.706749 -0.547023  1.000000 -0.551173  ... -0.126206 -0.004400
X15       0.536497  0.627591 -0.551173  1.000000  ... -0.048086 -0.060065
X16      -0.112770 -0.166095  0.058363 -0.102214  ...  0.175894  0.046570
X1_X1-1  -0.839902 -0.747858  0.600245 -0.428287  ... -0.199047  0.067425
X1_X1-2   0.839902  0.747858 -0.600245  0.428287  ...  0.199047 -0.067425
X2_X2-1  -0.048473  0.007174 -0.040274 -0.066485  ...  0.169725  0.125899
X2_X2-2  -0.035236 -0.189608  0.065830 -0.083576  ... -0.128176 -0.109016
X2_X2-3   0.158975  0.369728 -0.059889  0.289197  ... -0.048873 -0.008120
X3_X3-1  -0.161369 -0.343508  0.088429 -0.083214  ...  0.062921  0.010454
X3_X3-2   0.062143  0.104005 -0.066506 -0.015326  ... -0.040416 -0.006715
X3_X3-3   0.153427  0.357302 -0.057638  0.122226  ... -0.046980 -0.007806
X3_X3-4   0.040599  0.029111 -0.006777  0.001802  ... -0.004951 -0.000823
X4_X4-1   0.000959  0.194773  0.032069  0.021942  ... -0.061059 -0.010736
X4_X4-2  -0.394975 -0.211584  0.272149 -0.276354  ... -0.014316  0.061795
X4_X4-3   0.061336  0.046031 -0.036796  0.029352  ... -0.025178 -0.004183
X4_X4-4  -0.127800 -0.200359  0.089804 -0.019671  ... -0.149810 -0.024891
X4_X4-5   0.321084  0.115808 -0.248793  0.087394  ...  0.250530 -0.028065
X4_X4-6   0.206293  0.174325 -0.151310  0.208888  ... -0.046434 -0.003686
X4_X4-7   0.109273  0.135252 -0.041842  0.113282  ... -0.056203 -0.009970
X5_X5-1  -0.816437 -0.591392  0.726493 -0.572280  ... -0.130190 -0.021631
X5_X5-10  0.080796 -0.023180 -0.033007 -0.021361  ... -0.015145 -0.002516
X5_X5-11  0.177006 -0.074316 -0.062570 -0.106666  ... -0.048961 -0.008135
X5_X5-12  0.177942 -0.078822 -0.096379 -0.084712  ... -0.068908 -0.011449
X5_X5-13 -0.241555 -0.156265  0.096405 -0.052567  ... -0.082124 -0.013645
X5_X5-14  0.060280 -0.016138 -0.014615 -0.006616  ... -0.007565 -0.001257
X5_X5-15  0.069661  0.134331 -0.057577  0.026970  ... -0.028141 -0.004676
X5_X5-16 -0.013634 -0.255267 -0.128672  0.264287  ... -0.064756 -0.010759
X5_X5-17  0.235932  0.607976 -0.153685  0.364583  ... -0.101218 -0.016818
X5_X5-18 -0.107466 -0.138878 -0.025024 -0.126521  ... -0.030557 -0.005077
X5_X5-19       NaN       NaN       NaN       NaN  ...       NaN       NaN
X5_X5-2   0.463249  0.338926 -0.319604  0.278906  ... -0.221145 -0.036744
X5_X5-20       NaN       NaN       NaN       NaN  ...       NaN       NaN
X5_X5-21  0.017542 -0.001273 -0.126206 -0.048086  ...  1.000000 -0.013421
X5_X5-22 -0.040036 -0.060995 -0.004400 -0.060065  ... -0.013421  1.000000
X5_X5-3   0.123980  0.114118 -0.064816 -0.017250  ... -0.031766 -0.005278
X5_X5-4   0.007323  0.003379 -0.004187 -0.001097  ... -0.002858 -0.000475
X5_X5-5  -0.097789 -0.059096 -0.025016 -0.054606  ... -0.017884 -0.002972
X5_X5-6  -0.039454 -0.027668 -0.016963 -0.019893  ... -0.009907 -0.001646
X5_X5-7  -0.007496 -0.011267 -0.004462 -0.009714  ... -0.002858 -0.000475
X5_X5-8  -0.063039 -0.028908 -0.020935 -0.019607  ... -0.013421 -0.002230
X5_X5-9  -0.002862 -0.075494  0.257506 -0.075216  ... -0.019217 -0.003193
Y        -0.607864 -0.640153  0.709622 -0.709226  ... -0.075854  0.117818

           X5_X5-3   X5_X5-4   X5_X5-5   X5_X5-6   X5_X5-7   X5_X5-8  \
X6       -0.037248  0.001207 -0.031645 -0.009187 -0.002437 -0.008074
X7        0.046204 -0.003642  0.082135 -0.041910  0.012291 -0.007717
X8        0.113389 -0.006012  0.003597 -0.022867  0.011056 -0.026668
X9       -0.047977  0.003964  0.171631 -0.071153 -0.004200 -0.085936
X10       0.070050  0.000568  0.053115  0.060109  0.003348  0.046511
X11       0.077139  0.005673 -0.024441  0.007098  0.004057  0.008847
X12       0.123980  0.007323 -0.097789 -0.039454 -0.007496 -0.063039
X13       0.114118  0.003379 -0.059096 -0.027668 -0.011267 -0.028908
X14      -0.064816 -0.004187 -0.025016 -0.016963 -0.004462 -0.020935
X15      -0.017250 -0.001097 -0.054606 -0.019893 -0.009714 -0.019607
X16      -0.001555 -0.001475 -0.087651 -0.048553 -0.014008 -0.065775
X1_X1-1  -0.078279 -0.007044  0.089849  0.049771  0.014360  0.067425
X1_X1-2   0.078279  0.007044 -0.089849 -0.049771 -0.014360 -0.067425
X2_X2-1  -0.037678 -0.003390 -0.021213 -0.011751 -0.003390 -0.015919
X2_X2-2   0.043351 -0.025929  0.024407  0.013520  0.003901  0.018315
X2_X2-3  -0.019220  0.058484 -0.010821 -0.005994 -0.001729 -0.008120
X3_X3-1  -0.131530  0.002227  0.013931 -0.047339  0.002227 -0.081080
X3_X3-2   0.220718 -0.001430 -0.008949  0.078402 -0.001430  0.131876
X3_X3-3  -0.018476 -0.001662 -0.010402 -0.005762 -0.001662 -0.007806
X3_X3-4  -0.001947 -0.000175 -0.001096 -0.000607 -0.000175 -0.000823
X4_X4-1  -0.021174 -0.002287  0.037939  0.153318  0.044234  0.207698
X4_X4-2  -0.066270  0.015145 -0.041787 -0.023148 -0.006678 -0.031358
X4_X4-3  -0.009902 -0.000891 -0.005575 -0.003088 -0.000891 -0.004183
X4_X4-4  -0.058915 -0.005301 -0.033170 -0.018374 -0.005301 -0.024891
X4_X4-5  -0.066427 -0.005977 -0.037399 -0.020717 -0.005977 -0.028065
X4_X4-6   0.234286 -0.003641 -0.022784 -0.012621 -0.003641 -0.017097
X4_X4-7   0.071582 -0.002123  0.242155 -0.007360 -0.002123 -0.009970
X5_X5-1  -0.051199 -0.004607 -0.028826 -0.015968 -0.004607 -0.021631
X5_X5-10 -0.005956 -0.000536 -0.003353 -0.001858 -0.000536 -0.002516
X5_X5-11 -0.019255 -0.001733 -0.010841 -0.006005 -0.001733 -0.008135
X5_X5-12 -0.027099 -0.002438 -0.015257 -0.008452 -0.002438 -0.011449
X5_X5-13 -0.032297 -0.002906 -0.018183 -0.010073 -0.002906 -0.013645
X5_X5-14 -0.002975 -0.000268 -0.001675 -0.000928 -0.000268 -0.001257
X5_X5-15 -0.011067 -0.000996 -0.006231 -0.003451 -0.000996 -0.004676
X5_X5-16 -0.025466 -0.002291 -0.014338 -0.007942 -0.002291 -0.010759
X5_X5-17 -0.039806 -0.003582 -0.022411 -0.012414 -0.003582 -0.016818
X5_X5-18 -0.012017 -0.001081 -0.006766 -0.003748 -0.001081 -0.005077
X5_X5-19       NaN       NaN       NaN       NaN       NaN       NaN
X5_X5-2  -0.086969 -0.007825 -0.048964 -0.027123 -0.007825 -0.036744
X5_X5-20       NaN       NaN       NaN       NaN       NaN       NaN
X5_X5-21 -0.031766 -0.002858 -0.017884 -0.009907 -0.002858 -0.013421
X5_X5-22 -0.005278 -0.000475 -0.002972 -0.001646 -0.000475 -0.002230
X5_X5-3   1.000000 -0.001124 -0.007033 -0.003896 -0.001124 -0.005278
X5_X5-4  -0.001124  1.000000 -0.000633 -0.000351 -0.000101 -0.000475
X5_X5-5  -0.007033 -0.000633  1.000000 -0.002193 -0.000633 -0.002972
X5_X5-6  -0.003896 -0.000351 -0.002193  1.000000 -0.000351 -0.001646
X5_X5-7  -0.001124 -0.000101 -0.000633 -0.000351  1.000000 -0.000475
X5_X5-8  -0.005278 -0.000475 -0.002972 -0.001646 -0.000475  1.000000
X5_X5-9  -0.007557 -0.000680 -0.004255 -0.002357 -0.000680 -0.003193
Y        -0.033592 -0.007278 -0.025232 -0.019322 -0.010116 -0.024401

           X5_X5-9         Y
X6       -0.031391 -0.376066
X7       -0.078621 -0.520050
X8       -0.082401 -0.448213
X9        0.385619 -0.179513
X10      -0.101415 -0.667452
X11      -0.110711 -0.747957
X12      -0.002862 -0.607864
X13      -0.075494 -0.640153
X14       0.257506  0.709622
X15      -0.075216 -0.709226
X16      -0.008047  0.054002
X1_X1-1   0.096543  0.483213
X1_X1-2  -0.096543 -0.483213
X2_X2-1  -0.022793 -0.029614
X2_X2-2   0.026225  0.073223
X2_X2-3  -0.011627 -0.094132
X3_X3-1   0.014969  0.098154
X3_X3-2  -0.009615  0.031472
X3_X3-3  -0.011177 -0.154302
X3_X3-4  -0.001178 -0.015720
X4_X4-1  -0.015373 -0.003149
X4_X4-2  -0.041640  0.225506
X4_X4-3  -0.005990 -0.041472
X4_X4-4  -0.035641  0.023204
X4_X4-5  -0.036764 -0.078723
X4_X4-6   0.045929 -0.178767
X4_X4-7   0.193864 -0.085931
X5_X5-1  -0.030973  0.710433
X5_X5-10 -0.003603 -0.017440
X5_X5-11 -0.011648  0.110300
X5_X5-12 -0.016394  0.169055
X5_X5-13 -0.019538 -0.052828
X5_X5-14 -0.001800 -0.016077
X5_X5-15 -0.006695 -0.062968
X5_X5-16 -0.015406 -0.197441
X5_X5-17 -0.024081 -0.248466
X5_X5-18 -0.007270  0.080516
X5_X5-19       NaN       NaN
X5_X5-2  -0.052612 -0.362699
X5_X5-20       NaN       NaN
X5_X5-21 -0.019217 -0.075854
X5_X5-22 -0.003193  0.117818
X5_X5-3  -0.007557 -0.033592
X5_X5-4  -0.000680 -0.007278
X5_X5-5  -0.004255 -0.025232
X5_X5-6  -0.002357 -0.019322
X5_X5-7  -0.000680 -0.010116
X5_X5-8  -0.003193 -0.024401
X5_X5-9   1.000000  0.084212
Y         0.084212  1.000000

[50 rows x 50 columns]

In [15]:
corr_matrix[ "Y" ]

X6         -0.376066
X7         -0.520050
X8         -0.448213
X9         -0.179513
X10        -0.667452
X11        -0.747957
X12        -0.607864
X13        -0.640153
X14         0.709622
X15        -0.709226
X16         0.054002
X1_X1-1     0.483213
X1_X1-2    -0.483213
X2_X2-1    -0.029614
X2_X2-2     0.073223
X2_X2-3    -0.094132
X3_X3-1     0.098154
X3_X3-2     0.031472
X3_X3-3    -0.154302
X3_X3-4    -0.015720
X4_X4-1    -0.003149
X4_X4-2     0.225506
X4_X4-3    -0.041472
X4_X4-4     0.023204
X4_X4-5    -0.078723
X4_X4-6    -0.178767
X4_X4-7    -0.085931
X5_X5-1     0.710433
X5_X5-10   -0.017440
X5_X5-11    0.110300
X5_X5-12    0.169055
X5_X5-13   -0.052828
X5_X5-14   -0.016077
X5_X5-15   -0.062968
X5_X5-16   -0.197441
X5_X5-17   -0.248466
X5_X5-18    0.080516
X5_X5-19         NaN
X5_X5-2    -0.362699
X5_X5-20         NaN
X5_X5-21   -0.075854
X5_X5-22    0.117818
X5_X5-3    -0.033592
X5_X5-4    -0.007278
X5_X5-5    -0.025232
X5_X5-6    -0.019322
X5_X5-7    -0.010116
X5_X5-8    -0.024401
X5_X5-9     0.084212
Y           1.000000
Name: Y, dtype: float64

In [16]:
import numpy as np
Y_corr = corr_matrix[ "Y" ][ (-np.abs(corr_matrix[ "Y" ])).argsort() ] 
Y_corr

X5_X5-8    -0.024401
X11        -0.747957
X5_X5-1     0.710433
X14         0.709622
X15        -0.709226
X10        -0.667452
X13        -0.640153
X12        -0.607864
X7         -0.520050
X1_X1-1     0.483213
X1_X1-2    -0.483213
X8         -0.448213
X6         -0.376066
X5_X5-19         NaN
X5_X5-17   -0.248466
X4_X4-2     0.225506
X5_X5-16   -0.197441
X9         -0.179513
X4_X4-6    -0.178767
X5_X5-12    0.169055
X3_X3-3    -0.154302
X5_X5-20         NaN
X5_X5-11    0.110300
X3_X3-1     0.098154
X2_X2-3    -0.094132
X4_X4-7    -0.085931
X5_X5-7    -0.010116
X5_X5-18    0.080516
X4_X4-5    -0.078723
X5_X5-2    -0.362699
X2_X2-2     0.073223
X5_X5-15   -0.062968
X16         0.054002
X5_X5-13   -0.052828
X4_X4-3    -0.041472
X5_X5-21   -0.075854
X3_X3-2     0.031472
Y           1.000000
X2_X2-1    -0.029614
Y           1.000000
X5_X5-3    -0.033592
X5_X5-6    -0.019322
X4_X4-4     0.023204
X5_X5-4    -0.007278
X5_X5-10   -0.017440
X5_X5-14   -0.016077
X3_X3-4    -0.015720
X5_X5-5    -0.025232
X5_X5-22    0.117818
X4_X4-1    -0.003149
Name: Y, dtype: float64

* Q1: What's the most important correlation coefficients in terms of absolute magnitude with respect to the column Y.
    * Ans: X11

* Q2: Does it make a difference as compared with the numerical features only? 
    * Ans: After adding categorical features, the most significant positive correlation shifts from X14 to X5_X5-1. However, in terms of negative correlation, X11 still maintains its maximum influence.

## (c)
* After dropping non-significant variables at once for the liner regression model, what are the training and testing metrics of RMSE and r2_score for the new linear regression model? 
* Are the performance indexes improved as compared with those of the numerical features only?

In [17]:
import statsmodels.api as sm
X_train = train_data.iloc[:, : 11]
Y_train = train_data.iloc[:, 11]
X_train_aug = sm.add_constant(X_train) # Add coefficients for the intercept to become augmented matrix
est = sm.OLS(Y_train, X_train_aug).fit() 
# Ordinary least squares (最小平方法)
print(est.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                X1_X1-1   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     7711.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:00   Log-Likelihood:                 4614.2
No. Observations:                9888   AIC:                            -9204.
Df Residuals:                    9876   BIC:                            -9118.
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9425      0.009    104.211      0.000       0.925       0.960
X6             1.5519      0.089     17.418      0.000       1.377       1.727
X7             0.1873      0.014     13.107      0.000       0.159       0.215
X8            -0.2051      0.012    -16.936      0.000      -0.229      -0.181
X9             0.9007      0.021     43.041      0.000       0.860       0.942
X10            2.7378      0.039     70.326      0.000       2.661       2.814
X11           -1.6034      0.037    -42.833      0.000      -1.677      -1.530
X12           -2.0554      0.019   -110.556      0.000      -2.092      -2.019
X13           -0.7910      0.023    -33.766      0.000      -0.837      -0.745
X14            0.2445      0.013     19.440      0.000       0.220       0.269
X15            0.1503      0.018      8.206      0.000       0.114       0.186
X16           -0.1264      0.013    -10.012      0.000      -0.151      -0.102
==============================================================================
Omnibus:                     2680.580   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            58325.754
Skew:                           0.778   Prob(JB):                         0.00
Kurtosis:                      14.796   Cond. No.                         74.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
X_train_signif = pd.DataFrame(X_train, columns = throughput.columns[ 6 :]).drop("X7", axis= 1)
X_train_signif.head()

,X6,X8,X9,X10,X11,X12,X13,X14,X15,X16
1232,0.002395,0.072243,0.091429,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,0.166667
2271,0.016920,0.174905,0.291429,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,0.166667
1455,0.002559,0.077947,0.085714,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,0.166667
804,0.008010,0.319392,0.214286,0.157895,0.105263,0.216049,0.000000,0.088481,0.015789,0.333333
10163,0.015305,0.338403,0.255714,0.289474,0.342105,0.493827,0.409922,0.008347,0.263158,0.666667

In [19]:
X_train_signif = pd.DataFrame(X_train, columns = throughput.columns[ 6 :]).drop("X7", axis= 1)
X_train_signif = sm.add_constant(X_train_signif) # Add coefficients for the intercept
est_significant = sm.OLS(Y_train, X_train_signif.values).fit() 
# Ordinary least squares (最小平方法)
print( est_significant.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                X1_X1-1   R-squared:                       0.894
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     8321.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:00   Log-Likelihood:                 4528.9
No. Observations:                9888   AIC:                            -9036.
Df Residuals:                    9877   BIC:                            -8957.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9600      0.009    106.387      0.000       0.942       0.978
x1             1.3972      0.089     15.686      0.000       1.223       1.572
x2            -0.1601      0.012    -13.669      0.000      -0.183      -0.137
x3             0.8265      0.020     40.675      0.000       0.787       0.866
x4             2.8184      0.039     72.692      0.000       2.742       2.894
x5            -1.4600      0.036    -40.435      0.000      -1.531      -1.389
x6            -2.0660      0.019   -110.283      0.000      -2.103      -2.029
x7            -0.7432      0.023    -31.843      0.000      -0.789      -0.697
x8             0.2572      0.013     20.330      0.000       0.232       0.282
x9             0.1294      0.018      7.031      0.000       0.093       0.165
x10           -0.1607      0.012    -12.892      0.000      -0.185      -0.136
==============================================================================
Omnibus:                     2974.183   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            48985.479
Skew:                           1.004   Prob(JB):                         0.00
Kurtosis:                      13.718   Cond. No.                         72.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
from statsmodels.tools.eval_measures import rmse 
from sklearn.metrics import r2_score
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
print('train RMSE: ', round(rmse( Y_train , est_significant.predict(X_train_signif) ), 4)) 
print('train R^2: ', round(r2_score( Y_train, est_significant.predict(X_train_signif) ), 4)) 


# Need to drop nonsignificant columns from test_data
X3_test = pd.DataFrame(test_data.iloc[:, : ], columns = throughput.columns[ 6 :]).drop("X7", axis= 1)
X3_test = sm.add_constant(X3_test) # Add coefficients for the intercept
print('test RMSE: ',  round(rmse( test_data['Y'] , est_significant.predict(X3_test) ), 4)) 
print('test R^2: ', round(r2_score( test_data['Y'], est_significant.predict(X3_test) ), 4))

train RMSE:  0.1531
train R^2:  0.8939
test RMSE:  672.3261
test R^2:  -1.1393

In [21]:
est.rsquared

0.8957135068680173

In [22]:
est_significant.rsquared

0.8938993723427809

* Q1: After dropping non-significant variables, what are the training and testing metrics of RMSE and r2_score for the new linear regression model? 
    * Ans:
        * train RMSE: 245.9784
        * train R^2: 0.7161
        * test RMSE: 252.0665
        * test R^2: 0.6993

* Q2: Are the performance indexes improved as compared with those of the numerical features only?
    * Ans: Yes, it improved from 0.7161082629542501 to 0.7160983210526781.

## (d)
* If you add nonlinear features, e.g., 𝑥2, √𝑥, or log( 𝑥 + 0.00001) for each feature, do your RMSE and R2 scores improve over those of (c)? 
* If you use 3 nonlinear feature for each feature, then you will have 4 features for each one. In this case, data exploration might help to gain insight about the format of your nonlinear functions. You could write a function to automate the process of generating many features from 1 feature or the whole dataframe. 
    * (Hint: For a given feature vector x, the command to generate a nonlinear features is to use NumPy function, e.g. np.sqrt(x). For a given dataframe df, you need to use df.columns to access its column names.)

In [23]:
throughput.head()

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16
0,1546.836248,X1-1,X2-1,X3-1,X4-1,X5-1,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,0.8
1,1261.722593,X1-1,X2-1,X3-1,X4-1,X5-1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,0.8
2,860.853275,X1-1,X2-1,X3-1,X4-1,X5-1,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,0.8
3,887.356349,X1-1,X2-1,X3-1,X4-1,X5-1,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,0.8
4,895.059756,X1-1,X2-1,X3-1,X4-1,X5-1,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,0.8

In [24]:
throughput.iloc[:, 6:]

             X6   X7   X8   X9   X10   X11   X12  X13   X14  X15  X16
0      0.025286   50   48  105   3.0   2.0  0.45    8  1600    8  0.8
1      0.034876   67   34  105   3.0   2.0  0.45    8  1600   10  0.8
2      0.079237  176  187  200   8.0   6.0  0.75    8   216   10  0.8
3      0.113288  176  187  200   8.0   6.0  0.75    8   216   10  0.8
4      0.113778  176  187  200   8.0   6.0  0.75    8   216   10  0.8
...         ...  ...  ...  ...   ...   ...   ...  ...   ...  ...  ...
13181  0.149699  479  247   60  12.0  18.0  1.20  132    60   88  0.8
13182  0.300309  217  216   80   8.0  10.5  1.00  162   168  126  0.7
13183  0.300309  217  216   80   8.0  10.5  1.00  162   168   26  0.7
13184  0.154297  370  327  150  10.0  14.5  0.80  200    70  182  0.7
13185  0.163640  370  327  150  10.0  14.5  0.80  200    70  182  0.7

[13185 rows x 11 columns]

In [25]:
throughput_new = throughput.iloc[:, 6:].copy()
throughput_new

             X6   X7   X8   X9   X10   X11   X12  X13   X14  X15  X16
0      0.025286   50   48  105   3.0   2.0  0.45    8  1600    8  0.8
1      0.034876   67   34  105   3.0   2.0  0.45    8  1600   10  0.8
2      0.079237  176  187  200   8.0   6.0  0.75    8   216   10  0.8
3      0.113288  176  187  200   8.0   6.0  0.75    8   216   10  0.8
4      0.113778  176  187  200   8.0   6.0  0.75    8   216   10  0.8
...         ...  ...  ...  ...   ...   ...   ...  ...   ...  ...  ...
13181  0.149699  479  247   60  12.0  18.0  1.20  132    60   88  0.8
13182  0.300309  217  216   80   8.0  10.5  1.00  162   168  126  0.7
13183  0.300309  217  216   80   8.0  10.5  1.00  162   168   26  0.7
13184  0.154297  370  327  150  10.0  14.5  0.80  200    70  182  0.7
13185  0.163640  370  327  150  10.0  14.5  0.80  200    70  182  0.7

[13185 rows x 11 columns]

In [26]:
for i in range(6, 17):
    throughput_new["X" + str(i) + "_2"] = throughput_new["X" + str(i)] ** 2

throughput_new

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X7_2,X8_2,X9_2,X10_2,X11_2,X12_2,X13_2,X14_2,X15_2,X16_2
0,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,...,2500,2304,11025,9.0,4.00,0.2025,64,2560000,64,0.64
1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,...,4489,1156,11025,9.0,4.00,0.2025,64,2560000,100,0.64
2,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,...,30976,34969,40000,64.0,36.00,0.5625,64,46656,100,0.64
3,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,...,30976,34969,40000,64.0,36.00,0.5625,64,46656,100,0.64
4,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,...,30976,34969,40000,64.0,36.00,0.5625,64,46656,100,0.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13181,0.149699,479,247,60,12.0,18.0,1.20,132,60,88,...,229441,61009,3600,144.0,324.00,1.4400,17424,3600,7744,0.64
13182,0.300309,217,216,80,8.0,10.5,1.00,162,168,126,...,47089,46656,6400,64.0,110.25,1.0000,26244,28224,15876,0.49
13183,0.300309,217,216,80,8.0,10.5,1.00,162,168,26,...,47089,46656,6400,64.0,110.25,1.0000,26244,28224,676,0.49
13184,0.154297,370,327,150,10.0,14.5,0.80,200,70,182,...,136900,106929,22500,100.0,210.25,0.6400,40000,4900,33124,0.49
13185,0.163640,370,327,150,10.0,14.5,0.80,200,70,182,...,136900,106929,22500,100.0,210.25,0.6400,40000,4900,33124,0.49

In [27]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
X2_scaled = ss.fit_transform(throughput_new)
X2_scaled.shape

(13185, 22)

In [28]:
new_data = pd.concat([pd.DataFrame(X2_scaled, columns = throughput_new.columns[ 0 :]), 
                  pd.DataFrame(throughput['Y'].values, columns = [throughput.columns[0]])], axis = 1) 
new_data.head(2) # See the result and make sure that the above command works!

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X8_2,X9_2,X10_2,X11_2,X12_2,X13_2,X14_2,X15_2,X16_2,Y
0,0.001773,0.057196,0.055133,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.010526,...,0.006549,0.015223,0.003133,0.0,0.010841,0.0,0.444443,0.000326,0.259259,1546.836248
1,0.002447,0.088561,0.028517,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.015789,...,0.002680,0.015223,0.003133,0.0,0.010841,0.0,0.444443,0.000570,0.259259,1261.722593

In [29]:
import numpy as np
def split_train_test(data, train_ratio, random_seed):
    # to make this notebook's output identical at every run
    np.random.seed(random_seed)
    shuffled_indices = np.random.permutation(len(data))
    train_set_size = int(len(data) * train_ratio)
    # partition
    train_indices = shuffled_indices[:train_set_size]
    test_indices = shuffled_indices[train_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

train2_data, test2_data = split_train_test(new_data, 0.75 , 128 )

train2_data.head(2)

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X8_2,X9_2,X10_2,X11_2,X12_2,X13_2,X14_2,X15_2,X16_2,Y
1232,0.002395,0.073801,0.072243,0.091429,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,...,0.009735,0.018743,0.003133,0.00000,0.036348,0.000000,0.444443,0.000570,0.12037,1307.817487
2271,0.016920,0.164207,0.174905,0.291429,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,...,0.040315,0.110743,0.020050,0.02005,0.143480,0.008062,0.004442,0.011856,0.12037,398.908415

In [30]:
import statsmodels.api as sm
X_train = train2_data.iloc[:, : 22]
Y_train = train2_data.iloc[:, 22]
X_train_aug = sm.add_constant(X_train) # Add coefficients for the intercept to become augmented matrix
est = sm.OLS(Y_train, X_train_aug).fit() 
# Ordinary least squares (最小平方法)
print(est.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.800
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     1794.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:01   Log-Likelihood:                -66733.
No. Observations:                9888   AIC:                         1.335e+05
Df Residuals:                    9865   BIC:                         1.337e+05
Df Model:                          22
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        887.0725     39.452     22.485      0.000     809.738     964.407
X6         -4327.2754    173.604    -24.926      0.000   -4667.574   -3986.977
X7          -260.6635     77.230     -3.375      0.001    -412.050    -109.277
X8           -20.1351     68.236     -0.295      0.768    -153.891     113.621
X9           544.7224     98.176      5.548      0.000     352.278     737.167
X10         -748.3617    241.360     -3.101      0.002   -1221.477    -275.246
X11           30.7192    247.917      0.124      0.901    -455.249     516.688
X12         1420.5679    187.534      7.575      0.000    1052.963    1788.172
X13        -2775.3360     99.266    -27.959      0.000   -2969.917   -2580.755
X14          910.8022    107.545      8.469      0.000     699.992    1121.612
X15        -3178.3387     67.599    -47.018      0.000   -3310.846   -3045.831
X16         1392.2930    201.995      6.893      0.000     996.341    1788.245
X6_2        4322.6805    285.610     15.135      0.000    3762.826    4882.535
X7_2         148.5043     82.222      1.806      0.071     -12.667     309.676
X8_2          62.1694     66.113      0.940      0.347     -67.426     191.765
X9_2       -1095.5790    166.705     -6.572      0.000   -1422.356    -768.802
X10_2       -435.5989    462.041     -0.943      0.346   -1341.293     470.095
X11_2       1054.8291    466.782      2.260      0.024     139.842    1969.816
X12_2      -1103.1703    219.051     -5.036      0.000   -1532.554    -673.786
X13_2       3908.2189    164.470     23.762      0.000    3585.824    4230.614
X14_2       -587.4591     95.435     -6.156      0.000    -774.531    -400.387
X15_2       3825.8737     92.753     41.248      0.000    3644.058    4007.689
X16_2      -1807.2672    238.880     -7.566      0.000   -2275.522   -1339.013
==============================================================================
Omnibus:                     3578.448   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            66988.257
Skew:                           1.258   Prob(JB):                         0.00
Kurtosis:                      15.501   Cond. No.                         419.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
p_value_thres = 0.05 # threshold
nonsignificant = [] # A list of nonsignificant variables. It is empty initially.
significant = throughput_new.columns[ 0 :].tolist() # The initial significant variables
for i in range(len(throughput_new.columns[ 0 :])): 
    if est.pvalues[i+1] >= p_value_thres:
        # Add the nonsignificant variable to the list of nonsignificant variables
        nonsignificant.append(throughput_new.columns[ 0 +i]) 
        # Remove the nonsignificant variable out of the list of significant variables
        significant.remove(throughput_new.columns[ 0 +i])

print(nonsignificant, significant)

['X8', 'X11', 'X7_2', 'X8_2', 'X10_2'] ['X6', 'X7', 'X9', 'X10', 'X12', 'X13', 'X14', 'X15', 'X16', 'X6_2', 'X9_2', 'X11_2', 'X12_2', 'X13_2', 'X14_2', 'X15_2', 'X16_2']

In [32]:
X_train_signif = pd.DataFrame(X_train, columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis = 1)
X_train_signif.head(2)

,X6,X7,X9,X10,X12,X13,X14,X15,X16,X6_2,X9_2,X11_2,X12_2,X13_2,X14_2,X15_2,X16_2
1232,0.002395,0.073801,0.091429,0.026316,0.092593,0.000000,0.666110,0.015789,0.166667,0.000006,0.018743,0.00000,0.036348,0.000000,0.444443,0.000570,0.12037
2271,0.016920,0.164207,0.291429,0.105263,0.277778,0.073107,0.065109,0.100000,0.166667,0.000286,0.110743,0.02005,0.143480,0.008062,0.004442,0.011856,0.12037

In [33]:
from sklearn.linear_model import LinearRegression
  
lr = LinearRegression()
lr.fit(X_train_signif,Y_train)
# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
#     normalize=False)

lr.score(X_train_signif,Y_train)

0.7998601023377987

In [34]:
X_train_signif = pd.DataFrame(X_train, columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis= 1)
X_train_signif = sm.add_constant(X_train_signif) # Add coefficients for the intercept
est_significant = sm.OLS(Y_train, X_train_signif.values).fit() 
# Ordinary least squares (最小平方法)
print( est_significant.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.800
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     2320.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:01   Log-Likelihood:                -66738.
No. Observations:                9888   AIC:                         1.335e+05
Df Residuals:                    9870   BIC:                         1.336e+05
Df Model:                          17
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        888.2869     30.605     29.024      0.000     828.295     948.279
x1         -4381.5510    164.040    -26.710      0.000   -4703.103   -4059.999
x2          -106.6979     21.463     -4.971      0.000    -148.770     -64.626
x3           571.8432     89.969      6.356      0.000     395.485     748.201
x4         -1003.8040     65.309    -15.370      0.000   -1131.824    -875.784
x5          1357.0660    178.035      7.622      0.000    1008.080    1706.052
x6         -2757.8150     88.938    -31.008      0.000   -2932.152   -2583.478
x7           871.1191     90.534      9.622      0.000     693.654    1048.585
x8         -3172.4450     62.475    -50.780      0.000   -3294.908   -3049.982
x9          1458.8366    192.741      7.569      0.000    1081.025    1836.648
x10         4381.1733    280.043     15.645      0.000    3832.233    4930.114
x11        -1155.1906    151.228     -7.639      0.000   -1451.629    -858.753
x12         1132.3174     98.655     11.477      0.000     938.932    1325.702
x13        -1022.2534    210.090     -4.866      0.000   -1434.074    -610.433
x14         3892.3072    156.077     24.938      0.000    3586.365    4198.249
x15         -545.8081     87.281     -6.253      0.000    -716.897    -374.719
x16         3827.4943     86.951     44.019      0.000    3657.052    3997.937
x17        -1883.8945    229.538     -8.207      0.000   -2333.836   -1433.952
==============================================================================
Omnibus:                     3571.256   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            66333.371
Skew:                           1.257   Prob(JB):                         0.00
Kurtosis:                      15.437   Cond. No.                         189.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [35]:
from statsmodels.tools.eval_measures import rmse 
from sklearn.metrics import r2_score
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
print('train RMSE: ', round(rmse( Y_train, est_significant.predict( X_train_signif ) ), 4)) 
print('train R^2: ', round(r2_score( Y_train, est_significant.predict( X_train_signif ) ), 4)) 


# Need to drop nonsignificant columns from test_data
X3_test = pd.DataFrame(test2_data.iloc[:, : ], columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis= 1)
X3_test = sm.add_constant(X3_test) # Add coefficients for the intercept
print('test RMSE: ',  round(rmse( test2_data['Y'], est_significant.predict(X3_test) ), 4)) 
print('test R^2: ', round(r2_score( test2_data['Y'], est_significant.predict(X3_test )), 4))

train RMSE:  206.5284
train R^2:  0.7999
test RMSE:  218.1844
test R^2:  0.7747

* Q1: If you add nonlinear features, e.g., 𝑥2, √𝑥, or log( 𝑥 + 0.00001) for each feature, do your RMSE and R2 scores improve over those of (c)?
    * Ans: 
        * The former result:<br>
            train RMSE:  245.9784<br>
            train R^2:  0.7161<br>
            test RMSE:  252.0665<br>
            test R^2:  0.6993<br>
        * Change to:<br>
            train RMSE:  206.5284<br>
            train R^2:  0.7999<br>
            test RMSE:  218.1844<br>
            test R^2:  0.7747<br>

In [36]:
for i in range(6, 17):
    throughput_new["X" + str(i) + "_3"] = throughput_new["X" + str(i)] ** 3

throughput_new

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X7_3,X8_3,X9_3,X10_3,X11_3,X12_3,X13_3,X14_3,X15_3,X16_3
0,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,...,125000,110592,1157625,27.0,8.000,0.091125,512,4096000000,512,0.512
1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,...,300763,39304,1157625,27.0,8.000,0.091125,512,4096000000,1000,0.512
2,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,...,5451776,6539203,8000000,512.0,216.000,0.421875,512,10077696,1000,0.512
3,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,...,5451776,6539203,8000000,512.0,216.000,0.421875,512,10077696,1000,0.512
4,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,...,5451776,6539203,8000000,512.0,216.000,0.421875,512,10077696,1000,0.512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13181,0.149699,479,247,60,12.0,18.0,1.20,132,60,88,...,109902239,15069223,216000,1728.0,5832.000,1.728000,2299968,216000,681472,0.512
13182,0.300309,217,216,80,8.0,10.5,1.00,162,168,126,...,10218313,10077696,512000,512.0,1157.625,1.000000,4251528,4741632,2000376,0.343
13183,0.300309,217,216,80,8.0,10.5,1.00,162,168,26,...,10218313,10077696,512000,512.0,1157.625,1.000000,4251528,4741632,17576,0.343
13184,0.154297,370,327,150,10.0,14.5,0.80,200,70,182,...,50653000,34965783,3375000,1000.0,3048.625,0.512000,8000000,343000,6028568,0.343
13185,0.163640,370,327,150,10.0,14.5,0.80,200,70,182,...,50653000,34965783,3375000,1000.0,3048.625,0.512000,8000000,343000,6028568,0.343

In [37]:
for i in range(6, 17):
    throughput_new["X" + str(i) + "_sqrt"] = throughput_new["X" + str(i)] * np.sqrt(2)


throughput_new

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X7_sqrt,X8_sqrt,X9_sqrt,X10_sqrt,X11_sqrt,X12_sqrt,X13_sqrt,X14_sqrt,X15_sqrt,X16_sqrt
0,0.025286,50,48,105,3.0,2.0,0.45,8,1600,8,...,70.710678,67.882251,148.492424,4.242641,2.828427,0.636396,11.313708,2262.741700,11.313708,1.131371
1,0.034876,67,34,105,3.0,2.0,0.45,8,1600,10,...,94.752309,48.083261,148.492424,4.242641,2.828427,0.636396,11.313708,2262.741700,14.142136,1.131371
2,0.079237,176,187,200,8.0,6.0,0.75,8,216,10,...,248.901587,264.457936,282.842712,11.313708,8.485281,1.060660,11.313708,305.470129,14.142136,1.131371
3,0.113288,176,187,200,8.0,6.0,0.75,8,216,10,...,248.901587,264.457936,282.842712,11.313708,8.485281,1.060660,11.313708,305.470129,14.142136,1.131371
4,0.113778,176,187,200,8.0,6.0,0.75,8,216,10,...,248.901587,264.457936,282.842712,11.313708,8.485281,1.060660,11.313708,305.470129,14.142136,1.131371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13181,0.149699,479,247,60,12.0,18.0,1.20,132,60,88,...,677.408296,349.310750,84.852814,16.970563,25.455844,1.697056,186.676190,84.852814,124.450793,1.131371
13182,0.300309,217,216,80,8.0,10.5,1.00,162,168,126,...,306.884343,305.470129,113.137085,11.313708,14.849242,1.414214,229.102597,237.587878,178.190909,0.989949
13183,0.300309,217,216,80,8.0,10.5,1.00,162,168,26,...,306.884343,305.470129,113.137085,11.313708,14.849242,1.414214,229.102597,237.587878,36.769553,0.989949
13184,0.154297,370,327,150,10.0,14.5,0.80,200,70,182,...,523.259018,462.447835,212.132034,14.142136,20.506097,1.131371,282.842712,98.994949,257.386868,0.989949
13185,0.163640,370,327,150,10.0,14.5,0.80,200,70,182,...,523.259018,462.447835,212.132034,14.142136,20.506097,1.131371,282.842712,98.994949,257.386868,0.989949

In [38]:
from sklearn.preprocessing import MinMaxScaler
ss = MinMaxScaler()
X2_scaled = ss.fit_transform(throughput_new)
X2_scaled.shape

(13185, 44)

In [39]:
new_data = pd.concat([pd.DataFrame(X2_scaled, columns = throughput_new.columns[ 0 :]), 
                  pd.DataFrame(throughput['Y'].values, columns = [throughput.columns[0]])], axis = 1) 
new_data.head(2) # See the result and make sure that the above command works!

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X8_sqrt,X9_sqrt,X10_sqrt,X11_sqrt,X12_sqrt,X13_sqrt,X14_sqrt,X15_sqrt,X16_sqrt,Y
0,0.001773,0.057196,0.055133,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.010526,...,0.055133,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.010526,0.333333,1546.836248
1,0.002447,0.088561,0.028517,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.015789,...,0.028517,0.078571,0.026316,0.0,0.030864,0.0,0.66611,0.015789,0.333333,1261.722593

In [40]:
import numpy as np
def split_train_test(data, train_ratio, random_seed):
    # to make this notebook's output identical at every run
    np.random.seed(random_seed)
    shuffled_indices = np.random.permutation(len(data))
    train_set_size = int(len(data) * train_ratio)
    # partition
    train_indices = shuffled_indices[:train_set_size]
    test_indices = shuffled_indices[train_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

train2_data, test2_data = split_train_test(new_data, 0.75 , 128 )

train2_data.head(2)

,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,...,X8_sqrt,X9_sqrt,X10_sqrt,X11_sqrt,X12_sqrt,X13_sqrt,X14_sqrt,X15_sqrt,X16_sqrt,Y
1232,0.002395,0.073801,0.072243,0.091429,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,...,0.072243,0.091429,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,0.166667,1307.817487
2271,0.016920,0.164207,0.174905,0.291429,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,...,0.174905,0.291429,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,0.166667,398.908415

In [41]:
import statsmodels.api as sm
X_train = train2_data.iloc[:, : -1]
Y_train = train2_data.iloc[:, -1]
X_train_aug = sm.add_constant(X_train) # Add coefficients for the intercept to become augmented matrix
est = sm.OLS(Y_train, X_train_aug).fit() 
# Ordinary least squares (最小平方法)
print(est.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.843
Model:                            OLS   Adj. R-squared:                  0.842
Method:                 Least Squares   F-statistic:                     1598.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:01   Log-Likelihood:                -65552.
No. Observations:                9888   AIC:                         1.312e+05
Df Residuals:                    9854   BIC:                         1.314e+05
Df Model:                          33
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        890.7742     63.582     14.010      0.000     766.140    1015.409
X6         -2816.2924    158.452    -17.774      0.000   -3126.890   -2505.695
X7          -295.9241    103.826     -2.850      0.004    -499.444     -92.404
X8            18.4746     86.725      0.213      0.831    -151.524     188.473
X9           240.8148    148.127      1.626      0.104     -49.544     531.173
X10          941.2569    263.759      3.569      0.000     424.235    1458.279
X11         3172.3534    331.615      9.566      0.000    2522.321    3822.386
X12        -2566.5118    265.689     -9.660      0.000   -3087.316   -2045.707
X13        -3173.7790    115.475    -27.485      0.000   -3400.134   -2947.424
X14         -254.6024    111.204     -2.289      0.022    -472.586     -36.619
X15        -2593.2228     68.578    -37.814      0.000   -2727.649   -2458.797
X16         5150.4484    749.183      6.875      0.000    3681.896    6619.001
X6_2        1.972e+04   2903.143      6.794      0.000     1.4e+04    2.54e+04
X7_2         963.5857    482.548      1.997      0.046      17.692    1909.479
X8_2        -296.9734    384.126     -0.773      0.439   -1049.938     455.992
X9_2         754.0418    994.725      0.758      0.448   -1195.823    2703.907
X10_2      -9848.0688   1947.811     -5.056      0.000   -1.37e+04   -6029.961
X11_2      -1.579e+04   2346.228     -6.732      0.000   -2.04e+04   -1.12e+04
X12_2       1.512e+04   1343.773     11.252      0.000    1.25e+04    1.78e+04
X13_2        1.41e+04    675.151     20.879      0.000    1.28e+04    1.54e+04
X14_2       3388.8942    399.045      8.493      0.000    2606.684    4171.105
X15_2       1.242e+04    384.085     32.347      0.000    1.17e+04    1.32e+04
X16_2      -2.316e+04   3470.316     -6.672      0.000      -3e+04   -1.64e+04
X6_3       -1.431e+04   2636.819     -5.427      0.000   -1.95e+04   -9141.669
X7_3        -509.9298    324.083     -1.573      0.116   -1145.199     125.340
X8_3         249.5443    255.885      0.975      0.329    -252.043     751.131
X9_3       -2697.1930    907.636     -2.972      0.003   -4476.345    -918.041
X10_3       5160.2231   2425.718      2.127      0.033     405.320    9915.126
X11_3       1.433e+04   2723.416      5.262      0.000    8993.483    1.97e+04
X12_3       -1.11e+04    968.078    -11.468      0.000    -1.3e+04   -9204.392
X13_3      -8141.5126    535.575    -15.201      0.000   -9191.350   -7091.675
X14_3      -2318.0719    233.688     -9.920      0.000   -2776.149   -1859.995
X15_3      -8042.4559    296.101    -27.161      0.000   -8622.875   -7462.037
X16_3       1.305e+04   2059.021      6.338      0.000    9014.298    1.71e+04
X6_sqrt    -2816.2924    158.452    -17.774      0.000   -3126.890   -2505.695
X7_sqrt     -295.9241    103.826     -2.850      0.004    -499.444     -92.404
X8_sqrt       18.4746     86.725      0.213      0.831    -151.524     188.473
X9_sqrt      240.8148    148.127      1.626      0.104     -49.544     531.173
X10_sqrt     941.2569    263.759      3.569      0.000     424.235    1458.279
X11_sqrt    3172.3534    331.615      9.566      0.000    2522.321    3822.386
X12_sqrt   -2566.5118    265.689     -9.660      0.000   -3087.316   -2045.707
X13_sqrt   -3173.7790    115.475    -27.485      0.000   -3400.134   -2947.424
X14_sqrt    -254.6024    111.204     -2.289      0.022    -472.586     -36.619
X15_sqrt   -2593.2228     68.578    -37.814      0.000   -2727.649   -2458.797
X16_sqrt    5150.4484    749.183      6.875      0.000    3681.896    6619.001
==============================================================================
Omnibus:                     3447.977   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            85730.750
Skew:                           1.112   Prob(JB):                         0.00
Kurtosis:                      17.253   Cond. No.                     4.21e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.31e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [42]:
p_value_thres = 0.05 # threshold
nonsignificant = [] # A list of nonsignificant variables. It is empty initially.
significant = throughput_new.columns[ 0 :].tolist() # The initial significant variables
for i in range(len(throughput_new.columns[ 0 :])): 
    if est.pvalues[i+1] >= p_value_thres:
        # Add the nonsignificant variable to the list of nonsignificant variables
        nonsignificant.append(throughput_new.columns[ 0 +i]) 
        # Remove the nonsignificant variable out of the list of significant variables
        significant.remove(throughput_new.columns[ 0 +i])

print(nonsignificant, significant)

['X8', 'X9', 'X8_2', 'X9_2', 'X7_3', 'X8_3', 'X8_sqrt', 'X9_sqrt'] ['X6', 'X7', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X6_2', 'X7_2', 'X10_2', 'X11_2', 'X12_2', 'X13_2', 'X14_2', 'X15_2', 'X16_2', 'X6_3', 'X9_3', 'X10_3', 'X11_3', 'X12_3', 'X13_3', 'X14_3', 'X15_3', 'X16_3', 'X6_sqrt', 'X7_sqrt', 'X10_sqrt', 'X11_sqrt', 'X12_sqrt', 'X13_sqrt', 'X14_sqrt', 'X15_sqrt', 'X16_sqrt']

In [43]:
X_train_signif = pd.DataFrame(X_train, columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis = 1)
X_train_signif.head(2)

,X6,X7,X10,X11,X12,X13,X14,X15,X16,X6_2,...,X16_3,X6_sqrt,X7_sqrt,X10_sqrt,X11_sqrt,X12_sqrt,X13_sqrt,X14_sqrt,X15_sqrt,X16_sqrt
1232,0.002395,0.073801,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,0.166667,0.000006,...,0.083995,0.002395,0.073801,0.026316,0.000000,0.092593,0.000000,0.666110,0.015789,0.166667
2271,0.016920,0.164207,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,0.166667,0.000286,...,0.083995,0.016920,0.164207,0.105263,0.105263,0.277778,0.073107,0.065109,0.100000,0.166667

In [44]:
from sklearn.linear_model import LinearRegression
  
lr = LinearRegression()
lr.fit(X_train_signif,Y_train)
# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
#     normalize=False)

lr.score(X_train_signif,Y_train)

0.838668439491531

In [45]:
X_train_signif = pd.DataFrame(X_train, columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis= 1)
X_train_signif = sm.add_constant(X_train_signif) # Add coefficients for the intercept
est_significant = sm.OLS(Y_train, X_train_signif.values).fit() 
# Ordinary least squares (最小平方法)
print( est_significant.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.839
Model:                            OLS   Adj. R-squared:                  0.839
Method:                 Least Squares   F-statistic:                     1904.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:02   Log-Likelihood:                -65659.
No. Observations:                9888   AIC:                         1.314e+05
Df Residuals:                    9860   BIC:                         1.316e+05
Df Model:                          27
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        954.6126     60.566     15.762      0.000     835.891    1073.334
x1         -2637.2392    155.164    -16.996      0.000   -2941.392   -2333.086
x2          -173.5683     36.225     -4.791      0.000    -244.577    -102.559
x3           825.8506    258.004      3.201      0.001     320.110    1331.591
x4          3020.8570    329.201      9.176      0.000    2375.555    3666.159
x5         -2217.7525    257.863     -8.600      0.000   -2723.217   -1712.288
x6         -3066.6223    116.129    -26.407      0.000   -3294.259   -2838.986
x7          -366.0580    110.274     -3.320      0.001    -582.218    -149.898
x8         -2548.5810     68.471    -37.221      0.000   -2682.798   -2414.364
x9          5553.2999    741.695      7.487      0.000    4099.426    7007.174
x10         1.795e+04   2896.456      6.196      0.000    1.23e+04    2.36e+04
x11          134.6665     86.465      1.557      0.119     -34.823     304.156
x12        -8215.5483   1891.368     -4.344      0.000   -1.19e+04   -4508.079
x13        -1.536e+04   2334.489     -6.579      0.000   -1.99e+04   -1.08e+04
x14         1.391e+04   1327.686     10.476      0.000    1.13e+04    1.65e+04
x15         1.287e+04    672.889     19.120      0.000    1.15e+04    1.42e+04
x16         3828.7425    398.759      9.602      0.000    3047.093    4610.393
x17         1.215e+04    384.480     31.612      0.000    1.14e+04    1.29e+04
x18        -2.546e+04   3438.073     -7.405      0.000   -3.22e+04   -1.87e+04
x19        -1.288e+04   2634.568     -4.888      0.000    -1.8e+04   -7714.390
x20         -507.3781     86.665     -5.854      0.000    -677.259    -337.497
x21         2053.0778   2352.687      0.873      0.383   -2558.669    6664.825
x22         1.495e+04   2706.842      5.523      0.000    9644.216    2.03e+04
x23        -1.053e+04    964.118    -10.923      0.000   -1.24e+04   -8641.618
x24        -7125.9858    532.137    -13.391      0.000   -8169.083   -6082.888
x25        -2580.3454    234.474    -11.005      0.000   -3039.962   -2120.729
x26        -7866.2502    296.567    -26.524      0.000   -8447.582   -7284.919
x27         1.464e+04   2040.810      7.173      0.000    1.06e+04    1.86e+04
x28        -2637.2392    155.164    -16.996      0.000   -2941.392   -2333.086
x29         -173.5683     36.225     -4.791      0.000    -244.577    -102.559
x30          825.8506    258.004      3.201      0.001     320.110    1331.591
x31         3020.8570    329.201      9.176      0.000    2375.555    3666.159
x32        -2217.7525    257.863     -8.600      0.000   -2723.217   -1712.288
x33        -3066.6223    116.129    -26.407      0.000   -3294.259   -2838.986
x34         -366.0580    110.274     -3.320      0.001    -582.218    -149.898
x35        -2548.5810     68.471    -37.221      0.000   -2682.798   -2414.364
x36         5553.2999    741.695      7.487      0.000    4099.426    7007.174
==============================================================================
Omnibus:                     3417.823   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            86204.472
Skew:                           1.093   Prob(JB):                         0.00
Kurtosis:                      17.299   Cond. No.                     2.81e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.53e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [46]:
from statsmodels.tools.eval_measures import rmse 
from sklearn.metrics import r2_score
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html
print('train RMSE: ', round(rmse( Y_train, est_significant.predict( X_train_signif ) ), 4)) 
print('train R^2: ', round(r2_score( Y_train, est_significant.predict( X_train_signif ) ), 4)) 


# Need to drop nonsignificant columns from test_data
X3_test = pd.DataFrame(test2_data.iloc[:, : ], columns = throughput_new.columns[ 0 :]).drop(nonsignificant, axis= 1)
X3_test = sm.add_constant(X3_test) # Add coefficients for the intercept
print('test RMSE: ',  round(rmse( test2_data['Y'], est_significant.predict(X3_test) ), 4)) 
print('test R^2: ', round(r2_score( test2_data['Y'], est_significant.predict(X3_test )), 4))

train RMSE:  185.1833
train R^2:  0.8391
test RMSE:  196.2489
test R^2:  0.8177

* Q2: If you use 3 nonlinear feature for each feature, then you will have 4 features for each one. In this case, data exploration might help to gain insight about the format of your nonlinear functions. You could write a function to automate the process of generating many features from 1 feature or the whole dataframe. 
    * Ans: 
        * The former result:<br>
            train RMSE:  245.9784<br>
            train R^2:  0.7161<br>
            test RMSE:  252.0665<br>
            test R^2:  0.6993<br>
        * Add one nonlinear feature will change to:<br>
            train RMSE:  206.5284<br>
            train R^2:  0.7999<br>
            test RMSE:  218.1844<br>
            test R^2:  0.7747<br>
        * And add three nonlinear features will change to:<br>
            train RMSE:  185.1833<br>
            train R^2:  0.8391<br>
            test RMSE:  196.2489<br>
            test R^2:  0.8177<br>

## (e) Bonus
* For problem (c), please use the formal backward elimination procedure to eliminate non-significant variables.<br>
* In this case, you need to write a function which choose the most non-significant variable with the largest number and use for loop to call the function until there is no non-significant variable.

In [47]:
import statsmodels.api as sm
X_train = train_data.iloc[:, : 11]
Y_train = train_data.iloc[:, 11]
X_train_aug = sm.add_constant(X_train) # Add coefficients for the intercept to become augmented matrix
est = sm.OLS(Y_train, X_train_aug).fit() 
# Ordinary least squares (最小平方法)
print(est.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                X1_X1-1   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     7711.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:02   Log-Likelihood:                 4614.2
No. Observations:                9888   AIC:                            -9204.
Df Residuals:                    9876   BIC:                            -9118.
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9425      0.009    104.211      0.000       0.925       0.960
X6             1.5519      0.089     17.418      0.000       1.377       1.727
X7             0.1873      0.014     13.107      0.000       0.159       0.215
X8            -0.2051      0.012    -16.936      0.000      -0.229      -0.181
X9             0.9007      0.021     43.041      0.000       0.860       0.942
X10            2.7378      0.039     70.326      0.000       2.661       2.814
X11           -1.6034      0.037    -42.833      0.000      -1.677      -1.530
X12           -2.0554      0.019   -110.556      0.000      -2.092      -2.019
X13           -0.7910      0.023    -33.766      0.000      -0.837      -0.745
X14            0.2445      0.013     19.440      0.000       0.220       0.269
X15            0.1503      0.018      8.206      0.000       0.114       0.186
X16           -0.1264      0.013    -10.012      0.000      -0.151      -0.102
==============================================================================
Omnibus:                     2680.580   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            58325.754
Skew:                           0.778   Prob(JB):                         0.00
Kurtosis:                      14.796   Cond. No.                         74.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [48]:
p_value_thres = 0.05 # threshold
nonsignificant = [] # A list of nonsignificant variables. It is empty initially.
significant = throughput.columns[ 6 :].tolist() # The initial significant variables
for i in range(len(throughput.columns[ 6 :])): 
    if est.pvalues[i+1] >= p_value_thres:
        # Add the nonsignificant variable to the list of nonsignificant variables
        nonsignificant.append(throughput.columns[ 6 +i]) 
        # Remove the nonsignificant variable out of the list of significant variables
        significant.remove(throughput.columns[ 6 +i])

print(nonsignificant, significant)

[] ['X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16']

In [49]:
X_train_signif = pd.DataFrame(X_train, columns = throughput.columns[ 6 :]).drop(nonsignificant, axis= 1)
X_train_signif = sm.add_constant(X_train_signif) # Add coefficients for the intercept
est_significant = sm.OLS(Y_train, X_train_signif.values).fit() 
# Ordinary least squares (最小平方法)
print( est_significant.summary() )

                            OLS Regression Results
==============================================================================
Dep. Variable:                X1_X1-1   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     7711.
Date:                Wed, 18 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:34:02   Log-Likelihood:                 4614.2
No. Observations:                9888   AIC:                            -9204.
Df Residuals:                    9876   BIC:                            -9118.
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9425      0.009    104.211      0.000       0.925       0.960
x1             1.5519      0.089     17.418      0.000       1.377       1.727
x2             0.1873      0.014     13.107      0.000       0.159       0.215
x3            -0.2051      0.012    -16.936      0.000      -0.229      -0.181
x4             0.9007      0.021     43.041      0.000       0.860       0.942
x5             2.7378      0.039     70.326      0.000       2.661       2.814
x6            -1.6034      0.037    -42.833      0.000      -1.677      -1.530
x7            -2.0554      0.019   -110.556      0.000      -2.092      -2.019
x8            -0.7910      0.023    -33.766      0.000      -0.837      -0.745
x9             0.2445      0.013     19.440      0.000       0.220       0.269
x10            0.1503      0.018      8.206      0.000       0.114       0.186
x11           -0.1264      0.013    -10.012      0.000      -0.151      -0.102
==============================================================================
Omnibus:                     2680.580   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            58325.754
Skew:                           0.778   Prob(JB):                         0.00
Kurtosis:                      14.796   Cond. No.                         74.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.